---
title: StableLLaVA
subtitle: Enhanced Visual Instruction Tuning with Synthesized Image-Dialogue Data
---
author: Yanda Li, [Chi Zhang](https://icoz69.github.io/), Gang Yu, Zhibin Wang, Bin Fu, Guosheng Lin, Chunhua Shen, Ling Chen, Yunchao Wei

